#MIT License
#
#Copyright (c) 2024 Michele Maione
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
name: cygnus2
description: "love but open-source"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 20.24.0315+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  age_calculator: ^1.0.0
  cloud_firestore: ^4.15.9
  community_charts_flutter: ^1.0.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  email_validator: ^2.1.17
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter_markdown: ^0.6.21
  flutter_profile_picture: ^2.0.0
  json_annotation: ^4.8.1
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/documents/privacy_policy.md
    - assets/documents/terms_and_conditions.md
    - assets/icon/MAD.png
    - assets/images/clean.png
    - assets/images/chair.png
    - assets/images/all.png
    - assets/images/dev.png